name: menu
description: "A combined Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2  
  provider: 6.1.2
  dio: ^5.7.0
  equatable: ^2.0.0
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  supabase_flutter: ^2.8.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/12.png
    - assets/images/13.png
    - assets/images/14.png
    - assets/images/15.png
    - assets/images/16.png
    - assets/images/100.png
    - assets/images/200.png
    - assets/images/300.png
    - assets/images/400.png
    - assets/images/500.png
    - assets/images/600.png
    - assets/images/700.png
    - assets/images/800.png
  
  fonts:
    - family: Russo One
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf
    - family: Tektur
      fonts:
        - asset: assets/fonts/Tektur-Regular.ttf
        - asset: assets/fonts/Tektur-Bold.ttf
          weight: 700